language: node_js
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
- '6'
env:
  global:
    secure: zn10PoglN38Wf57bGMk3hsGgoVCPoPAg9dkEA6xA3YnTcsR3JQtwC2FfBPYHzcyTSewLyJre/XonekslDdlpL+vHTTC0L3JhjT0DLD9rxolcIs0t58eb+47IPC5MJ7vEldspp9a7Rg2fLVAyAna0wmpxpu3dGgYKQFpKhJwfDAfm7y009EFHc7vx7AG9wMxxT8MMpuWxx3URZCuzCAMMlIZarW/kkeJLu257cF065oHDVMFoDZh/ynJSUfvRMiwdAsCPitiwDTtL5CBJ64Sv7waibKBN7VDk1Bz5HyevtxFHUB1NDvtJX7jvS70ccV8yS89waWzi0f/f0Iw0OzK4Y2d2bgoIDRuQRlHmZgATQ55Mfzr0c/oTidQQBWqMjxU7B2+d2wawS2QfmfSvbz/TkimWXCZzvrwrT3Hbi5xxc1u1JZnKk06Rm0I8+JXjnSHDJEoEHRSfNcFewLhiX7R4lbXkhSxgxbrTIQDsEUmcG7wxsvQWyVmvR8BB7XcCLEaIUmF8mG9n867gOeD/xPvLemIZIfFXp6SXej2HYt978j0YCPnYVzReO9V6hsbVu4DdNMKd4nNrEK+fDu8u/XwNisxdgF14k9+1qF9So2PGspBZ68BnZO+G6Fbbj2ha13axE3YQOM1cu/qNbLZQzMFjspc3E9+l5WRPRmSnYabkPZw=
before_install:
  - npm install --global yarn --cache-min 999999999
install:
  - yarn
script:
  - yarn test
after_success:
  - ./deploy.sh
